---
- name: Ensure parent directories exist
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ ai_agents_config_agents }}"

- name: Copy agents configurations
  ansible.builtin.template:
    src: "{{ lookup('ansible.builtin.first_found', templates_candidates) }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  vars:
    templates_candidates:
      - "{{ inventory_dir }}/templates/{{ item.src }}"
      - "{{ item.src }}"
  loop: "{{ ai_agents_config_agents }}"
